server:
  port: 8087

spring:
  datasource:
    first:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://101.200.230.0:3306/xunlu_api?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&autoReconnect=true&useSSL=false
      username: root
      password: rtlbs2016Map
      type: com.alibaba.druid.pool.DruidDataSource
    second:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://60.205.94.208:3306/welfaremap?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&autoReconnect=true&useSSL=false
      username: root
      password: RTmap123!@#
      type: com.alibaba.druid.pool.DruidDataSource
#    ≤‚ ‘
#    second:
#      driver-class-name: com.mysql.jdbc.Driver
#      url: jdbc:mysql://123.56.132.58:3306/test?useUnicode=true&characterEncoding=utf-8&allowMultiQueries=true&autoReconnect=true&useSSL=false
#      username: root
#      password: RTmap123!@#
#      type: com.alibaba.druid.pool.DruidDataSource
  redis:
    database: 0
    host: 123.57.74.38
    port: 6379
    password: lbsredis123
mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.example.stringbootbo.bean
#logging:
#  level:
#    com.example.stringbootbo.mapper: info
logging:
  config: classpath:logback-boot.xml



